-- One row per Utah county and calendar year. FIPS stays text, including zeros.
CREATE TABLE county_annual (
    year INTEGER NOT NULL CHECK (year BETWEEN 2020 AND 2025),
    state_fips TEXT NOT NULL CHECK (state_fips = '49'),
    county_fips TEXT NOT NULL CHECK (length(county_fips) = 3),
    county_fips5 TEXT NOT NULL CHECK (length(county_fips5) = 5),
    county_name TEXT NOT NULL,
    single_family_units INTEGER NOT NULL CHECK (single_family_units >= 0),
    two_unit_units INTEGER NOT NULL CHECK (two_unit_units >= 0),
    three_four_unit_units INTEGER NOT NULL CHECK (three_four_unit_units >= 0),
    five_plus_unit_units INTEGER NOT NULL CHECK (five_plus_unit_units >= 0),
    total_buildings INTEGER NOT NULL CHECK (total_buildings >= 0),
    total_units INTEGER NOT NULL CHECK (total_units >= 0),
    multifamily_units INTEGER NOT NULL CHECK (multifamily_units >= 0),
    total_valuation_usd INTEGER NOT NULL CHECK (total_valuation_usd >= 0),
    reported_buildings INTEGER NOT NULL CHECK (reported_buildings >= 0),
    reported_units INTEGER NOT NULL CHECK (reported_units >= 0),
    reported_valuation_usd INTEGER NOT NULL CHECK (reported_valuation_usd >= 0),
    imputed_units INTEGER NOT NULL CHECK (imputed_units >= 0),
    imputed_unit_share REAL CHECK (imputed_unit_share BETWEEN 0 AND 1),
    period_role TEXT NOT NULL CHECK (period_role IN ('baseline', 'analysis')),
    coverage_basis TEXT NOT NULL,
    source_id TEXT NOT NULL,
    source_file TEXT NOT NULL,
    source_line INTEGER NOT NULL,
    PRIMARY KEY (county_fips5, year),
    CHECK (total_units = single_family_units + multifamily_units),
    CHECK (multifamily_units = two_unit_units + three_four_unit_units + five_plus_unit_units),
    CHECK (imputed_units = total_units - reported_units)
);
